### ISSUE TITLE
Variable Arguements supported by the Work type?

### ISSUE THREAD

**Issue by itzurabhi** [tghosgor/threadpool11#1]
Does the implementation support variable number of arguments and passing them into the worker function or lambda?

**Comment by tghosgor** [comment]
From the library's point of view, the worker function does not have any arguments. You can either use `std::bind` to bind arguments to a worker function or use capturing in lambda functions. Either way you will need to use mutexes to guard writes to shared variables.

**Comment by itzurabhi** [comment]
Thanks.
