### ISSUE TITLE
source file headers still reference GPLv3 licensing

### ISSUE THREAD

**Issue by pnav** [tghosgor/threadpool11#15]
Hello,

The README for threadpool11 indicates that it is now intended to be licensed under LGPLv3, but the headers on the individual source files still state they are licensed under GPLv3.  Could you please update the headers to remove this inconsistency? We would like to include threadpool11 in a project, but we cannot under GPL licensing. 

Thanks!

**Comment by tghosgor** [comment]
Thanks for the heads up. It is all LGPL-v2.1 now.
