### ISSUE TITLE
demo of threadpool11 vs openmp

### ISSUE THREAD

**Issue by Frandy** [tghosgor/threadpool11#16]
Thank you for sharing this project. 
I tried demo/src/openmp, threadpool11 takes 20s, and openmp takes 30s for 4core8thread machine, basic match with data shown in readme.
While I think it is not fair for openmp.  It take factorial as test function, and it cause imbalance of job when use openmp default schedule. If change to dynamic schedule, then openmp can get similar performance as threadpool11.
change as below:
-#pragma omp parallel for
+#pragma omp parallel for schedule(dynamic,1)

By the way, it report error when compile due to missing include <vector> for pool.cpp and demo/src/main.cpp.
Thank you for sharing again.

**Comment by tghosgor** [comment]
Thanks, fixed the includes and updated README.md to reflect the openmp situation.
