### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by insoulity** [tghosgor/threadpool11#17]
Hi there,

It's claimed that your design has a potential bug here (https://github.com/Fdhvdu/ThreadPool/tree/master/comparison). Do you have any idea what it meant and where?

**Comment by tghosgor** [comment]
It took me some time to run the tests in that test environment due to it lacking a proper build/run system.

It seems it is something about ctor/dtor. I will try to fix it.

3.0 branch should work fine without a fix.
