### ISSUE TITLE
pool.cpp:28:31: error: default initialization of an object of const type 'const pool::no_future_t' without a user-provided default constructor

### ISSUE THREAD

**Issue by rkorzeniewski** [tghosgor/threadpool11#18]
I'm having problem compiling threadpool11 on:
$ c++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by tghosgor** [comment]
Cannot reproduce it with clang 9.0.1 but I have added an empty constructor to pool::no_future_t which should fix this.

**Comment by rkorzeniewski** [comment]
Thanks.
