### ISSUE TITLE
compiling the code that uses threadpool11

### ISSUE THREAD

**Issue by Hrco123** [tghosgor/threadpool11#9]
Hello there, I am using your source file to create a thread pool and in my compiler i am getting the message:
undefined reference to 'threadpool11::Pool::Pool(unsigned long)'
undefined reference to 'threadpool11::Pool::~Pool()'
undefined reference to 'threadpool11::Pool::~Pool()'
What should I do? I am using codeblocks 10.05 on Ubuntu. Is there any library to include in the linker such as '-lthreadpool11'? 
Thank you (I know it is kind of nooby question)

**Comment by tghosgor** [comment]
I am sorry somehow I missed the issue ticket.

You have to compile and link the .cpp files together with your project. Or you can also install the library using 'cake && make install' and link with your project like you said (-lthreadpool11 flag).
